// Code generated by hertz generator.

package chat

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getchatmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}
