// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithMaxRequestBodySize(1024 * 1024 * 1024))

	register(h)
	h.Spin()
}
