// Code generated by hertz generator.

package chat

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"mini-Tiktok/biz/model/social/chat"
)

// GetChatMessage .
// @router /douyin/message/chat [GET]
func GetChatMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.DouyinMessageChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(chat.DouyinMessageChatResponse)

	c.JSON(consts.StatusOK, resp)
}

// PostMessage .
// @router /douyin/message/action [POST]
func PostMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.DouyinMessageActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(chat.DouyinMessageActionResponse)

	c.JSON(consts.StatusOK, resp)
}
