[database]
# todo： 等服务器部署后，修改此行
mysql_dsn = "tiktok:tiktok@tcp(tiktok-mysql:3306)/douyin?charset=utf8&parseTime=True&loc=Local"

[kodo]
bucket= "2568douyin"
domain= "http://ryi1c8rs5.hn-bkt.clouddn.com"