// Code generated by hertz generator.

package feed

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdouyinfeedMw() []app.HandlerFunc {
	// your code...
	return nil
}
