name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 3 * * *' # 每天3点执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Checkout to docker branch
        run: |
          git checkout -b docker
          git merge dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: cnflwzh
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose.yml
          push: true
          tags: registry.cn-beijing.aliyuncs.com/cnflwzh-docker/mini_tiktok:latest
          build-args:
            KODO_ACCESS_KEY: ${{ secrets.KODO_ACCESS_KEY }}
            KODO_SECRET_KEY: ${{ secrets.KODO_SECRET_KEY }}