// Code generated by hertz generator.

package relation

import (
	"github.com/cloudwego/hertz/pkg/app"
	"mini-Tiktok/biz/middleware/jwt"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationactionMw() []app.HandlerFunc {
	// your code...
	return jwt.JWTAuthMiddleware()
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationfollowlistMw() []app.HandlerFunc {
	//return []app.HandlerFunc{func(c context.Context, ctx *app.RequestContext) {
	//	var req relation.DouyinRelationFollowListRequest
	//	_, err := jwt.ParseToken(strconv.FormatInt(req.GetToken(), 10))
	//	if err != nil {
	//		ctx.Redirect(consts.StatusUnauthorized, []byte("/douyin/user/login/"))
	//		return
	//	}
	//}}
	return jwt.JWTAuthMiddleware()
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationfollowerlistMw() []app.HandlerFunc {
	// your code...
	//return []app.HandlerFunc{func(c context.Context, ctx *app.RequestContext) {
	//	var req relation.DouyinRelationFollowListRequest
	//	_, err := jwt.ParseToken(strconv.FormatInt(req.GetToken(), 10))
	//	if err != nil {
	//		ctx.Redirect(consts.StatusUnauthorized, []byte("/douyin/user/login/"))
	//		return
	//	}
	//}}
	return jwt.JWTAuthMiddleware()
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationfriendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
